"""Human-readable per-RIG execution plan format.

The text format is the canonical format generated by the Sequencer.
The parser reconstructs the schema-v2 in-memory document expected by the
existing runtime, so legacy JSON plans and new .plan files can coexist.
"""

from __future__ import annotations

import json
import re
import subprocess
import unicodedata
from copy import deepcopy
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable


FORMAT_VERSION = 1
PROJECT_ROOT = Path(__file__).resolve().parent.parent

_SAFE_NAME_RE = re.compile(r"[^A-Za-z0-9_-]+")
_MULTI_UNDERSCORE_RE = re.compile(r"_+")
_RIG_TOKEN_RE = re.compile(r"^RIG([1-4])$")
_PLAN_FILENAME_RE = re.compile(
    r"^exec_plan_(\d{8})_RIG([1-4])_"
    r"([A-Z0-9_]+)_(.+)\.(?:plan|json)$"
)

_BRAND_RULES = (
    ("SONY", "SONY"),
    ("NIKON", "NIKON"),
    ("CANON", "CANON"),
    ("FUJIFILM", "FUJIFILM"),
    ("FUJI", "FUJIFILM"),
    ("PANASONIC", "PANASONIC"),
    ("OM DIGITAL", "OM_SYSTEM"),
    ("OM SYSTEM", "OM_SYSTEM"),
    ("OLYMPUS", "OLYMPUS"),
    ("PENTAX", "PENTAX"),
    ("RICOH", "RICOH"),
    ("LEICA", "LEICA"),
    ("HASSELBLAD", "HASSELBLAD"),
    ("SIGMA", "SIGMA"),
)


class ExecutionPlanTextError(ValueError):
    pass


def _json_value(value: Any) -> str:
    return json.dumps(
        value,
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    )


def _decode_header_value(raw: str) -> Any:
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        return raw


def normalize_plan_name(value: Any) -> str:
    if not isinstance(value, str):
        raise ExecutionPlanTextError(
            "Execution Plan name must be text"
        )

    normalized = unicodedata.normalize("NFKD", value.strip())
    normalized = normalized.encode(
        "ascii",
        "ignore",
    ).decode("ascii")

    normalized = re.sub(r"\s+", "_", normalized)
    normalized = _SAFE_NAME_RE.sub("_", normalized)
    normalized = _MULTI_UNDERSCORE_RE.sub(
        "_",
        normalized,
    )
    normalized = normalized.strip("_-")

    if not normalized:
        raise ExecutionPlanTextError(
            "Execution Plan name is empty"
        )

    if len(normalized) > 80:
        raise ExecutionPlanTextError(
            "Execution Plan name is too long "
            "(80 characters maximum)"
        )

    return normalized


def canonical_camera_brand(manufacturer: Any) -> str:
    if (
        not isinstance(manufacturer, str)
        or not manufacturer.strip()
    ):
        raise ExecutionPlanTextError(
            "camera manufacturer is missing"
        )

    raw = " ".join(
        manufacturer.strip().upper().split()
    )

    for marker, brand in _BRAND_RULES:
        if marker in raw:
            return brand

    return normalize_plan_name(raw).upper()


def eclipse_date_yyyymmdd(
    circumstances: dict[str, Any],
) -> str:
    if not isinstance(circumstances, dict):
        raise ExecutionPlanTextError(
            "circumstances must be an object"
        )

    raw = (
        circumstances.get("_date")
        or circumstances.get("_date_utc")
        or circumstances.get("date")
        or circumstances.get("eclipse_date")
    )

    if not isinstance(raw, str):
        raise ExecutionPlanTextError(
            "eclipse date is missing"
        )

    match = re.match(
        r"^(\d{4})-(\d{2})-(\d{2})",
        raw.strip(),
    )

    if not match:
        raise ExecutionPlanTextError(
            "eclipse date is invalid"
        )

    return "".join(match.groups())


def _rig_camera(
    rig: dict[str, Any],
) -> dict[str, Any]:
    devices = rig.get("devices")

    camera = (
        devices.get("camera")
        if isinstance(devices, dict)
        else None
    )

    if not isinstance(camera, dict):
        raise ExecutionPlanTextError(
            f"RIG {rig.get('rig_id', '?')} "
            "camera is not configured"
        )

    return camera


def build_execution_plan_filename(
    *,
    circumstances: dict[str, Any],
    rig: dict[str, Any],
    plan_name: str,
) -> str:
    rig_id = rig.get("rig_id")

    if (
        not isinstance(rig_id, int)
        or isinstance(rig_id, bool)
        or not 1 <= rig_id <= 4
    ):
        raise ExecutionPlanTextError(
            "invalid RIG id"
        )

    camera = _rig_camera(rig)

    brand = canonical_camera_brand(
        camera.get("manufacturer")
        or camera.get("vendor")
        or camera.get("brand")
    )

    suffix = normalize_plan_name(plan_name)
    date = eclipse_date_yyyymmdd(circumstances)

    return (
        f"exec_plan_{date}_RIG{rig_id}_"
        f"{brand}_{suffix}.plan"
    )


def is_generated_plan_for_rig(
    filename: str,
    rig_id: int,
) -> bool:
    if (
        not isinstance(filename, str)
        or not isinstance(rig_id, int)
        or isinstance(rig_id, bool)
        or not 1 <= rig_id <= 4
    ):
        return False

    match = _PLAN_FILENAME_RE.match(filename)

    return bool(
        match
        and int(match.group(2)) == rig_id
    )


def build_software_metadata(
    project_root: str | Path | None = None,
) -> dict[str, Any]:
    root = (
        Path(project_root)
        if project_root is not None
        else PROJECT_ROOT
    )

    version = ""

    try:
        version = (
            root / "VERSION"
        ).read_text(
            encoding="utf-8"
        ).strip()
    except OSError:
        pass

    commit = ""

    try:
        commit = (
            root / "BUILD_COMMIT"
        ).read_text(
            encoding="utf-8"
        ).strip()
    except OSError:
        pass

    dirty: bool | None = None

    if not commit:
        try:
            commit = subprocess.check_output(
                [
                    "git",
                    "-C",
                    str(root),
                    "rev-parse",
                    "HEAD",
                ],
                text=True,
                stderr=subprocess.DEVNULL,
                timeout=2,
            ).strip()

            dirty = bool(
                subprocess.check_output(
                    [
                        "git",
                        "-C",
                        str(root),
                        "status",
                        "--porcelain",
                    ],
                    text=True,
                    stderr=subprocess.DEVNULL,
                    timeout=2,
                ).strip()
            )

        except (
            OSError,
            subprocess.SubprocessError,
        ):
            commit = ""

    result = {
        "solartrigger_version":
            version or "unknown",
        "solartrigger_commit":
            commit or "unknown",
    }

    if dirty is not None:
        result["working_tree_dirty"] = dirty

    return result


def _flatten(
    prefix: str,
    value: Any,
    *,
    max_depth: int = 8,
) -> Iterable[tuple[str, Any]]:
    if max_depth < 0:
        yield prefix, value
        return

    if isinstance(value, dict):
        if not value:
            yield prefix, {}
            return

        for key in sorted(
            value,
            key=lambda item: str(item),
        ):
            child = (
                str(key)
                .replace("\n", " ")
                .replace("\r", " ")
            )

            child_prefix = (
                f"{prefix}.{child}"
                if prefix
                else child
            )

            yield from _flatten(
                child_prefix,
                value[key],
                max_depth=max_depth - 1,
            )

        return

    if isinstance(value, (list, tuple)):
        yield prefix, list(value)
        return

    yield prefix, value


def _section(
    lines: list[str],
    title: str,
) -> None:
    lines.append("#")
    lines.append(
        f"# --- {title} "
        + "-" * max(1, 64 - len(title))
    )


def _append_flattened(
    lines: list[str],
    prefix: str,
    value: Any,
) -> None:
    for key, item in _flatten(
        prefix,
        value,
    ):
        lines.append(
            f"# {key}={_json_value(item)}"
        )


def _eclipse_summary(
    circumstances: dict[str, Any],
) -> dict[str, Any]:
    keys = (
        "_eclipse",
        "_type_global",
        "_type",
        "_magnitude",
        "_moon_sun_ratio",
        "_duration",
        "_sun_alt_tmax",
        "_date",
        "_date_utc",
        "title",
        "C1",
        "C2",
        "TMAX",
        "C3",
        "C4",
        "TSTART",
        "TEND",
        "C1_local",
        "C2_local",
        "TMAX_local",
        "C3_local",
        "C4_local",
        "C1_alt_deg",
        "C2_alt_deg",
        "TMAX_alt_deg",
        "C3_alt_deg",
        "C4_alt_deg",
    )

    return {
        key: deepcopy(circumstances[key])
        for key in keys
        if key in circumstances
    }


def _location_summary(
    circumstances: dict[str, Any],
) -> dict[str, Any]:
    location = circumstances.get(
        "_circumstances_location"
    )

    result = (
        deepcopy(location)
        if isinstance(location, dict)
        else {}
    )

    for source_key, target_key in (
        ("_timezone", "timezone"),
        ("_timezone_name", "timezone_name"),
        (
            "_utc_offset_minutes",
            "utc_offset_minutes",
        ),
    ):
        if source_key in circumstances:
            result[target_key] = deepcopy(
                circumstances[source_key]
            )

    return result


def _optimization_summary(
    exposure_opt: dict[str, Any],
    effective_rig: dict[str, Any],
    rig_id: int,
) -> dict[str, Any]:
    result: dict[str, Any] = {}

    if (
        "atmospheric_attenuation_enabled"
        in exposure_opt
    ):
        result[
            "atmospheric_attenuation_enabled"
        ] = deepcopy(
            exposure_opt[
                "atmospheric_attenuation_enabled"
            ]
        )

    rigs = exposure_opt.get("rigs")

    if isinstance(rigs, list):
        for entry in rigs:
            if (
                isinstance(entry, dict)
                and entry.get("rig_id") == rig_id
            ):
                result["selected_rig"] = (
                    deepcopy(entry)
                )
                break

    photo = effective_rig.get("photo")

    if isinstance(photo, dict):
        result["effective_photo"] = deepcopy(
            photo
        )

    return result


def render_execution_plan_text(
    plan: dict[str, Any],
    *,
    filename: str,
    context: dict[str, Any],
    generated_at: datetime | None = None,
    software: dict[str, Any] | None = None,
) -> str:
    if not isinstance(plan, dict):
        raise ExecutionPlanTextError(
            "execution plan must be an object"
        )

    if plan.get("schema_version") != 2:
        raise ExecutionPlanTextError(
            "execution plan schema must be 2"
        )

    if (
        plan.get("config_type")
        != "execution_plan"
    ):
        raise ExecutionPlanTextError(
            "invalid execution plan type"
        )

    commands = plan.get("commands")
    phases = plan.get("command_phases")

    if (
        not isinstance(commands, list)
        or not commands
    ):
        raise ExecutionPlanTextError(
            "execution plan contains no commands"
        )

    if (
        not isinstance(phases, list)
        or len(phases) != len(commands)
    ):
        raise ExecutionPlanTextError(
            "execution plan phase metadata "
            "is invalid"
        )

    rig_ids = {
        command.get("rig_id")
        for command in commands
        if isinstance(command, dict)
    }

    if len(rig_ids) != 1:
        raise ExecutionPlanTextError(
            "text execution plan must contain "
            "exactly one RIG"
        )

    rig_id = next(iter(rig_ids))

    if (
        not isinstance(rig_id, int)
        or isinstance(rig_id, bool)
        or not 1 <= rig_id <= 4
    ):
        raise ExecutionPlanTextError(
            "invalid RIG id in execution plan"
        )

    circumstances = context.get(
        "circumstances"
    )
    photo_setup = context.get(
        "photo_setup"
    )
    exposure_opt = context.get(
        "exposure_opt"
    )
    rig = context.get("rig")
    effective_rig = context.get(
        "effective_rig",
        rig,
    )

    for value, description in (
        (circumstances, "circumstances"),
        (photo_setup, "Photo Setup"),
        (
            exposure_opt,
            "Exposure Optimization",
        ),
        (rig, "RIG"),
        (effective_rig, "effective RIG"),
    ):
        if not isinstance(value, dict):
            raise ExecutionPlanTextError(
                f"{description} context is missing"
            )

    now = (
        generated_at
        or datetime.now(timezone.utc)
    )

    if now.tzinfo is None:
        now = now.replace(
            tzinfo=timezone.utc
        )

    now = now.astimezone(timezone.utc)

    software_info = dict(
        software
        if software is not None
        else build_software_metadata()
    )

    sources = deepcopy(
        plan.get("sources") or {}
    )

    timing_files = (
        plan.get("camera_timing_files")
        or {}
    )

    timing_file = (
        timing_files.get(str(rig_id))
        if isinstance(timing_files, dict)
        else None
    )

    if timing_file:
        sources[
            "camera_timing_file"
        ] = timing_file

    initial_all = (
        plan.get("initial_state_required")
        or {}
    )

    initial_state = (
        initial_all.get(
            str(rig_id),
            {},
        )
        if isinstance(initial_all, dict)
        else {}
    )

    generated_text = (
        now
        .isoformat(timespec="seconds")
        .replace("+00:00", "Z")
    )

    lines = [
        "# =============================================================================",
        "# SolarTrigger Execution Plan",
        "# =============================================================================",
        (
            "# plan.format_version="
            f"{FORMAT_VERSION}"
        ),
        (
            "# plan.generated_at_utc="
            f"{_json_value(generated_text)}"
        ),
        (
            "# plan.filename="
            f"{_json_value(filename)}"
        ),
        (
            "# plan.time_reference="
            f"{_json_value('UTC')}"
        ),
        f"# plan.rig_id={rig_id}",
        (
            "# plan.sequence_start_utc="
            f"{_json_value(plan.get('sequence_start_utc'))}"
        ),
        (
            "# plan.sequence_end_utc="
            f"{_json_value(plan.get('sequence_end_utc'))}"
        ),
        (
            "# plan.sequence_margin_min="
            f"{_json_value(plan.get('sequence_margin_min'))}"
        ),
    ]

    for key, value in sorted(
        software_info.items()
    ):
        lines.append(
            f"# plan.{key}="
            f"{_json_value(value)}"
        )

    _section(lines, "ECLIPSE")
    _append_flattened(
        lines,
        "eclipse",
        _eclipse_summary(circumstances),
    )

    _section(lines, "LOCATION")
    _append_flattened(
        lines,
        "location",
        _location_summary(circumstances),
    )

    _section(lines, "RIG")
    _append_flattened(
        lines,
        "rig",
        rig,
    )

    _section(lines, "PHOTO SETUP")
    _append_flattened(
        lines,
        "photo_setup",
        photo_setup,
    )

    _section(lines, "OPTIMIZATIONS")
    _append_flattened(
        lines,
        "optimization",
        _optimization_summary(
            exposure_opt,
            effective_rig,
            rig_id,
        ),
    )

    _section(lines, "SOURCES")
    _append_flattened(
        lines,
        "source",
        sources,
    )

    _section(lines, "RESULT")

    result = {
        "command_count": len(commands),
        "sequence_start_utc":
            plan.get("sequence_start_utc"),
        "sequence_end_utc":
            plan.get("sequence_end_utc"),
        "first_command_utc":
            commands[0].get("time_utc"),
        "last_command_utc":
            commands[-1].get("time_utc"),
    }

    _append_flattened(
        lines,
        "result",
        result,
    )

    _section(lines, "INITIAL STATE")

    lines.append(
        "# initial_state="
        + _json_value(
            initial_state
            if isinstance(
                initial_state,
                dict,
            )
            else {}
        )
    )

    lines.extend(
        [
            "#",
            "# =============================================================================",
            "# TIME | RIG | ACTION | PARAMETERS",
            "# =============================================================================",
        ]
    )

    marker = object()
    current_phase: Any = marker

    for phase, command in zip(
        phases,
        commands,
        strict=True,
    ):
        if phase != current_phase:
            lines.append(
                "# @phase="
                + _json_value(phase)
            )
            current_phase = phase

        if not isinstance(command, dict):
            raise ExecutionPlanTextError(
                "invalid command entry"
            )

        params = command.get("params")

        if not isinstance(params, dict):
            raise ExecutionPlanTextError(
                "command params must be "
                "an object"
            )

        lines.append(
            f"{command.get('time_utc')} | "
            f"RIG{command.get('rig_id')} | "
            f"{command.get('action')} | "
            f"{_json_value(params)}"
        )

    lines.append("")

    return "\n".join(lines)


def parse_execution_plan_text(
    text: str,
) -> dict[str, Any]:
    if not isinstance(text, str):
        raise ExecutionPlanTextError(
            "execution plan text is invalid"
        )

    header: dict[str, Any] = {}
    commands: list[dict[str, Any]] = []
    phases: list[Any] = []

    current_phase: Any = None

    for line_number, raw_line in enumerate(
        text.splitlines(),
        start=1,
    ):
        stripped = raw_line.strip()

        if not stripped:
            continue

        if stripped.startswith("#"):
            comment = stripped[1:].strip()

            if comment.startswith("@phase="):
                current_phase = (
                    _decode_header_value(
                        comment.split(
                            "=",
                            1,
                        )[1].strip()
                    )
                )
                continue

            if (
                "=" in comment
                and not comment.startswith("-")
            ):
                key, raw_value = (
                    comment.split("=", 1)
                )

                key = key.strip()

                if key:
                    header[key] = (
                        _decode_header_value(
                            raw_value.strip()
                        )
                    )

            continue

        parts = [
            item.strip()
            for item in raw_line.split(
                "|",
                3,
            )
        ]

        if len(parts) != 4:
            raise ExecutionPlanTextError(
                f"line {line_number}: expected "
                "TIME | RIG | ACTION | "
                "PARAMETERS"
            )

        (
            time_utc,
            rig_token,
            action,
            raw_params,
        ) = parts

        match = _RIG_TOKEN_RE.fullmatch(
            rig_token
        )

        if not match:
            raise ExecutionPlanTextError(
                f"line {line_number}: "
                "invalid RIG token"
            )

        rig_id = int(match.group(1))

        if action not in {"SET", "PHOTO"}:
            raise ExecutionPlanTextError(
                f"line {line_number}: "
                f"unsupported action {action!r}"
            )

        try:
            params = json.loads(raw_params)
        except json.JSONDecodeError as exc:
            raise ExecutionPlanTextError(
                f"line {line_number}: "
                "invalid parameters JSON"
            ) from exc

        if not isinstance(params, dict):
            raise ExecutionPlanTextError(
                f"line {line_number}: "
                "parameters must be an object"
            )

        commands.append(
            {
                "time_utc": time_utc,
                "rig_id": rig_id,
                "action": action,
                "params": params,
            }
        )

        phases.append(current_phase)

    if (
        header.get("plan.format_version")
        != FORMAT_VERSION
    ):
        raise ExecutionPlanTextError(
            "unsupported execution plan "
            "text format"
        )

    if (
        header.get("plan.time_reference")
        != "UTC"
    ):
        raise ExecutionPlanTextError(
            "execution plan time reference "
            "must be UTC"
        )

    header_rig_id = header.get(
        "plan.rig_id"
    )

    if (
        not isinstance(header_rig_id, int)
        or isinstance(header_rig_id, bool)
        or not 1 <= header_rig_id <= 4
    ):
        raise ExecutionPlanTextError(
            "execution plan header "
            "has invalid RIG"
        )

    if not commands:
        raise ExecutionPlanTextError(
            "execution plan contains no commands"
        )

    if any(
        command["rig_id"] != header_rig_id
        for command in commands
    ):
        raise ExecutionPlanTextError(
            "execution plan command/header "
            "RIG mismatch"
        )

    sources = {}

    for key, value in header.items():
        if key.startswith("source."):
            sources[
                key[len("source."):]
            ] = value

    initial_state = header.get(
        "initial_state",
        {},
    )

    if not isinstance(
        initial_state,
        dict,
    ):
        raise ExecutionPlanTextError(
            "execution plan initial_state "
            "must be an object"
        )

    sequence_start = header.get(
        "plan.sequence_start_utc"
    )
    sequence_end = header.get(
        "plan.sequence_end_utc"
    )

    if (
        not isinstance(sequence_start, str)
        or not isinstance(sequence_end, str)
    ):
        raise ExecutionPlanTextError(
            "execution plan sequence bounds "
            "are missing"
        )

    result = {
        "schema_version": 2,
        "config_type": "execution_plan",
        "sources": sources,
        "sequence_start_utc":
            sequence_start,
        "sequence_end_utc":
            sequence_end,
        "initial_state_required": {
            str(header_rig_id):
                deepcopy(initial_state),
        },
        "commands": commands,
        "command_phases": phases,
        "_text_header": header,
    }

    margin = header.get(
        "plan.sequence_margin_min"
    )

    if margin is not None:
        result[
            "sequence_margin_min"
        ] = margin

    return result


__all__ = [
    "FORMAT_VERSION",
    "ExecutionPlanTextError",
    "build_execution_plan_filename",
    "build_software_metadata",
    "canonical_camera_brand",
    "eclipse_date_yyyymmdd",
    "is_generated_plan_for_rig",
    "normalize_plan_name",
    "parse_execution_plan_text",
    "render_execution_plan_text",
]
