#!/bin/sh
set -eu
case "${1:-}" in
 check) /usr/bin/apt-get update; /usr/bin/apt-get --just-print upgrade;;
 upgrade) /usr/bin/apt-get update; DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get upgrade -y;;
 *) exit 64;;
esac
